### ISSUE TITLE
HTML样式问题

### ISSUE THREAD

**Issue by LovelyHaochi** [Sansui233/proxypool#12]
版本：v0.5.0 预编译版_amd64
问题：`index.html` 右下角客服框无法正常删除，在 `assets/html/index.html` 删除后重新执行二进制文件 `index.html` 还原回模板

**Comment by LovelyHaochi** [comment]
补充：
![](https://user-images.githubusercontent.com/49602236/100448874-f32b0f80-30ed-11eb-9ec8-06bd6d4b8ec5.png) 就是这个客服对话框

**Comment by LovelyHaochi** [comment]
@Sansui233 大佬快出来qaq

**Comment by Sansui233** [comment]
是这样的，html是和程序一起打包的，在运行的时候会恢复html文件出来，恢复html只是为了使用源代码的人方便修改后自己再次打包。运行时并不会使用本地的html文件。

**Comment by Sansui233** [comment]
It’s the way that is designed.

**Comment by LovelyHaochi** [comment]
Duplicate of #12
所以大佬如果我要把这个删掉我需要用 `编译运行` 是吗??qaq

**Comment by Sansui233** [comment]
> Duplicate of #12
> 所以大佬如果我要把这个删掉我需要用 `编译运行` 是吗??qaq

是的。编译前您还需要使用go-bindata打包一次，Note中有提到。

**Comment by LovelyHaochi** [comment]
> > Duplicate of #12
> > 所以大佬如果我要把这个删掉我需要用 `编译运行` 是吗??qaq
> 
> 是的。编译前您还需要使用go-bindata打包一次，Note中有提到。

谢谢！
