### ISSUE TITLE
部署到heroku时的一些问题

### ISSUE THREAD

**Issue by zyp997** [Sansui233/proxypool#13]
![微信截图_20201130211139](https://user-images.githubusercontent.com/53375741/100614270-d9d5cd80-3350-11eb-9071-402c7362c238.png)
如图，现在是只有6个抓取源吗？可用的节点一直是0。
而且在config文件中设置speedtest为ture时，依旧是不开启测速的？

**Comment by Sansui233** [comment]
1. 示例抓取源只有6个。节点为0的情况我一直不太清楚，还在查。
2. 在进行测速任务之前时都会显示未开启测速

**Comment by Sansui233** [comment]
已修复
