### ISSUE TITLE
ss订阅不显示国家

### ISSUE THREAD

**Issue by Alvin9999** [Sansui233/proxypool#15]
ss-sip002: https://proxypoolss.tk/sip002/sub

你好，这个订阅地址转化为节点导入到v2rayN软件中，国家名称显示为几个问号“????”

**Comment by Sansui233** [comment]
国家名称前面有emoji，请去V2RayN客户端下询问对emoji的支持。

如果您非常在意名称的问题且马上就要用，建议对clash节点筛选后，使用[订阅转换](https://bianyuan.xyz/)，在“进阶模式”中关闭emoji。

我所使用的qv2ray的V2ray-core可以正常显示带有emoji的名称。

如果您确认不是emoji导致的问题，请回复，否则之后会关闭此issue。
