### ISSUE TITLE
前端html 问题

### ISSUE THREAD

**Issue by iam7cn** [Sansui233/proxypool#18]

**Comment by Sansui233** [comment]
1. 是的，修改后需要手动打包、编译
2. 是的，但不是手动修改，而是由静态文件打包工具生成

修改方式在Note.md中提到了，这里照搬过来一下：

## Web界面

为了方便打包，原作者将静态的assets文件模板由zip压缩后存为字符串的形式，如

```
var _assetsHtmlSurgeHtml="[]byte("\x1f\x8b\x...")"
```

以上字节解压后是一个go的HTML模板。解压时，由gzip的reader写入byte.Buffer，再转换为Bytes写入相应文件。

静态文件打包工具见：[这里](https://github.com/go-bindata/go-bindata) 或 [这里](https://github.com/shuLhan/go-bindata) 。安装好以上工具中的任意一个，然后修改后assets下的html文件，修改好后执行docs里的shell脚本的第一行。之后编译即可。

根据原作者要求，请勿修改原作者版权信息。

**Comment by iam7cn** [comment]
Thanks，我来试一下。
