### ISSUE TITLE
[建议]大佬，是否考虑增加一个可能比heroku更好的平台fly.io

### ISSUE THREAD

**Issue by lsy1291455142** [Sansui233/proxypool#25]
## Description 描述
https://fly.io
刚刚在该平台上搭建了程序，貌似没发现什么问题
这是我搭建的链接https://proxypool.fly.dev
**需要绑卡**(tg频道分享的卡有的可以绑)1[SH BINS](https://t.me/shbins)     2[TEAM BINNERS](https://t.me/TeamBinnersOfficial)         3[𝘽𝙄𝙉𝙎 𝘾𝙍𝘼𝘾𝙆𝙄𝙉𝙂](https://t.me/BinsCracking)
这是使用方法和收费方式(免费额度就够用) https://jingyuan.wang/p/fly-io
速度比heroku快很多，而且**没有休眠**。
只需要在项目里增加一个文件fly.toml，参考https://fly.io/docs/getting-started/golang/
大佬可以考虑下
![1.jpg](https://i.loli.net/2021/02/14/MBUdrvt52Xub8sL.jpg)
![2.jpg](https://i.loli.net/2021/02/14/Hr6LXUvBhmD1Gye.jpg)

**Comment by Sansui233** [comment]
好的感谢建议，我去看下
