### ISSUE TITLE
网络抓取源仅仅只有7个

### ISSUE THREAD

**Issue by AndersonGhost** [Sansui233/proxypool#35]
- [ ] I'm using the newest release version, and bug isn't solved
  我使用的是最新的release版本，Bug仍未解决
- [ ] I've tested on the newest master, and bug isn't solved
  我测试的是最新master分支，Bug仍未解决
- [ ] I've searched the issues and there's not a similar one
  我已经查看过其他issue，没有类似的情况

Bug Version出现Bug的版本：v0.6.0 
Environment操作环境：debian 10
  
## Description 问题描述
在Debian 10 安装成功后，抓取源仅仅只有7个，请问这是何故？

网页上的显示为：
统计
目前共有抓取源 7 个， 全部节点 544 个，ss节点 197 个，ssr节点 83 个，vmess节点 236 个，trojan节点 28 个

可用节点数量：287

是否开启测速：已开启

最后更新时间：2021-02-22 09:53:06

**Comment by Sansui233** [comment]
因为确实只有7个示例订阅源，其他的需要自己添加

**Comment by AndersonGhost** [comment]
大佬，您好！ 可以分享一点订阅源吗？您的订阅源是48个啊

**Comment by Sansui233** [comment]
> 大佬，您好！ 可以分享一点订阅源吗？您的订阅源是48个啊

主要是仓库是程序为主，还有一些滥用问题，订阅源上个人不打算放太多。不过有人[在长期整理订阅源](https://i.sqeven.me/discuss/detail/100)，以后打算有关订阅源的东西放在 #37 中。
