### ISSUE TITLE
部署在Heroku后，该怎么修改订阅源呢？我在heroku部署的应用，用平台的远程控制台，找到了配置文件，但是不能用vim编辑，该要使用什么方法修改订阅源呢？希望大佬指点，谢谢。

### ISSUE THREAD

**Issue by ldj-network** [Sansui233/proxypool#46]
![image](https://user-images.githubusercontent.com/67744640/111892083-fa768000-8a32-11eb-958e-04d36329d240.png)

**Comment by Sansui233** [comment]
把配置文件和订阅源放在公网可获取的位置，配置文件中订阅源也是公网可获取的url。

然后改heroku app的setting中的Config Vars，CONFIG_FILE填写公网上的配置文件地址。
![image](https://user-images.githubusercontent.com/27474981/111901837-3a5e5700-8a75-11eb-91e4-d983aba4dc67.png)

**Comment by ldj-network** [comment]
> 将配置文件和订阅源放在公网可获取的位置，配置文件中订阅源也是公网可获取的网址。
> 
> 然后改heroku app的setting中的Config Vars，CONFIG_FILE填充公网上的配置文件地址。
> ![图像](https://user-images.githubusercontent.com/27474981/111901837-3a5e5700-8a75-11eb-91e4-d983aba4dc67.png)

感谢回复，我已解决，了解。
