### ISSUE TITLE
大佬你好，最新网站 https://proxypoolss.tk/ 上clash的订阅在openclash上无法正常转换。。。

### ISSUE THREAD

**Issue by caliban511** [Sansui233/proxypool#49]
## Description 描述
如题。
只要在订阅时使用“在线订阅转换”功能，则一定会提示“配置文件节点部分校验失败”，然后配置更新失败，日志显示如下：
2021-03-22 10:49:16 Error: Config 【proxypool】Update Error
2021-03-22 10:49:16 Error: Updated Config 【proxypool】 Has No Proxy Field, Update Exit...
2021-03-22 10:49:16 Error: Updated Config 【proxypool】 Has No Proxy Field
2021-03-22 10:49:18 Reload OpenClash Firewall Rules
2021-03-22 10:47:42 Error: Config 【proxypool】Update Error
2021-03-22 10:47:42 Error: Updated Config 【proxypool】 Has No Proxy Field, Update Exit...
2021-03-22 10:47:42 Error: Updated Config 【proxypool】 Has No Proxy Field

**Comment by Sansui233** [comment]
OpenClash和clash-core的配置文件字段好像不一样。我不知道是它没有更新clash-core还是说就是这么设计的，也不知道能不能兼容。我不用OpenClash不知道它的工作原理，可以去OpenClash问问。

**Comment by caliban511** [comment]
> 
> 
> OpenClash和clash-core的配置文件字段好像不一样。我不知道是它没有更新clash-core还是说就是这么设计的，也不知道能不能兼容。我不用OpenClash不知道它的工作原理，可以去OpenClash问问。

好的，感谢大佬回复。

**Comment by botnang** [comment]
我也遇到同样的问题，但是奇怪的是：
如果把从https://proxypoolss.tk/clash/config下载到的config文件重命名为config.yaml，然后作为配置文件上传它到openclash里，就是能够直接使用的（有“切换”启用按钮）。

而如果我上传未改名的config文件，openclash提示“验证通过”，却不会出现“切换”启用它的按钮。

**Comment by caliban511** [comment]
> 
> 
> 我也遇到同样的问题，但是奇怪的是：
> 如果把从 https://proxypoolss.tk/clash/config 下载到的config文件重命名为config.yaml，然后作为配置文件上传它到openclash里，就是能够直接使用的（有“切换”启用按钮）。
> 
> 而如果我上传未改名的config文件，openclash提示“验证通过”，却不会出现“切换”启用它的按钮。

兄弟，你们是怎么在openclash里使用这个项目的？我试着在本地搭建了一个，然后在openclash里，无论怎么弄都没办法正常使用，，，

**Comment by botnang** [comment]
> > 我也遇到同样的问题，但是奇怪的是：
> > 如果把从 https://proxypoolss.tk/clash/config 下载到的config文件重命名为config.yaml，然后作为配置文件上传它到openclash里，就是能够直接使用的（有“切换”启用按钮）。
> > 而如果我上传未改名的config文件，openclash提示“验证通过”，却不会出现“切换”启用它的按钮。
> 
> 兄弟，你们是怎么在openclash里使用这个项目的？我试着在本地搭建了一个，然后在openclash里，无论怎么弄都没办法正常使用，，，

openclash的主界面最右边有“运行日志“，应该有报错的具体信息。
我就是根据报错内容找到问题然后解决的。
搞不定的话建议去openclash开发页发帖求助
https://github.com/vernesong/OpenClash

**Comment by caliban511** [comment]
> > > 我也遇到同样的问题，但是奇怪的是：
> > > 如果把从 https://proxypoolss.tk/clash/config 下载到的config文件重命名为config.yaml，然后作为配置文件上传它到openclash里，就是能够直接使用的（有“切换”启用按钮）。
> > > 而如果我上传未改名的config文件，openclash提示“验证通过”，却不会出现“切换”启用它的按钮。
> > 
> > 
> > 兄弟，你们是怎么在openclash里使用这个项目的？我试着在本地搭建了一个，然后在openclash里，无论怎么弄都没办法正常使用，，，
> 
> openclash的主界面最右边有“运行日志“，应该有报错的具体信息。
> 我就是根据报错内容找到问题然后解决的。
> 搞不定的话建议去openclash开发页发帖求助
> https://github.com/vernesong/OpenClash

这个问题有日志也没用，日志显示的就是我上面说的内容，已经去开帖求助了。

**Comment by BruceLee569** [comment]
> OpenClash和clash-core的配置文件字段好像不一样。我不知道是它没有更新clash-core还是说就是这么设计的，也不知道能不能兼容。我不用OpenClash不知道它的工作原理，可以去OpenClash问问。

应该是网站响应文件没有返回文件名导致的，我用自己服务器部署的 subconverter 后端也不能正常转换，查看日志后发现卡在请求订阅链接那儿，建议网站服务的响应头里可以添加Content-Disposition字段，值为yaml后缀的clash配置文件名。

否则还得我们自己写两句代码下载到本地，然后提交本地文件给后端转换服务。

**Comment by caliban511** [comment]
> 
> 
> 应该是网站响应文件没有返回文件名导致的，我用自己服务器部署的 subconverter 后端也不能正常转换，查看日志后发现卡在请求订阅链接那儿，建议网站服务的响应头里可以添加Content-Disposition字段，值为yaml后缀的clash配置文件名。
> 否则还得我们自己写两句代码下载到本地，然后提交本地文件给后端转换服务。

感谢大佬回复，已经在本地安装docker版subconverter，问题算是解决了。谢谢。
